version: '3.4'

services:

  accomodationdb:
    container_name: accomodationdb
    restart: always
    ports:
      - "18007:27017"

  reservationdb:
    container_name: reservationdb
    restart: always
    ports:
     - "18005:27017"

  accomodation-service:
    container_name: accomodation-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AccomodationDatabase:ConnectionString=mongodb://accomodationdb:27017"
      - DatabaseName=AccomodationDB
    depends_on:
      - accomodationdb
    ports:
      - "5200:80"
      - "5201:80"

  reservation-service:
    container_name: reservation-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ReservationDatabase:ConnectionString=mongodb://reservationdb:27017"
      - DatabaseName=ReservationDB
      - "GrpcCheckAccomodations=http://accomodation-service:5201"
    depends_on:
      - reservationdb
    ports:
      - "5100:80"
      - "5101:443"
 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: accomodationdb
    depends_on:
      - accomodationdb

  mongo-express1:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: reservationdb
    depends_on:
      - reservationdb

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
