version: '3.4'

services:

  accomodationdb:
    container_name: accomodationdb
    restart: always
    ports:
      - "18007:27017"

  reservationdb:
    container_name: reservationdb
    restart: always
    ports:
     - "18005:27017"

  userdb:
    container_name: userdb
    restart: always
    ports:
     - "18006:27017"

  accomodation-service:
    container_name: Accomodations
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AccomodationDatabase:ConnectionString=mongodb://accomodationdb:27017"
      - DatabaseName=AccomodationDB
      - "GrpcGetHost=http://reservation-service:5101"
    depends_on:
      - accomodationdb
    ports:
      - "5200:80"
      - "5201:80"

  reservation-service:
    container_name: reservation-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ReservationDatabase:ConnectionString=mongodb://reservationdb:27017"
      - DatabaseName=ReservationDB
      - "GrpcGetHost=http://accomodation-service:5201"
      - "GrpcCheckRemovalEligibility=http://user-service:5401"
    depends_on:
      - reservationdb
    ports:
      - "5100:80"
      - "5101:443"

  user-service:
    container_name: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "UserDatabase:ConnectionString=mongodb://userdb:27017"
      - DatabaseName=UserDB
      - "GrpcCheckRemovalEligibility=http://reservation-service:5101"
    depends_on:
      - userdb
    ports:
      - "5400:80"
      - "5401:443"
 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: accomodationdb
    depends_on:
      - accomodationdb

  mongo-express1:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: reservationdb
    depends_on:
      - reservationdb

  mongo-express2:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: userdb
    depends_on:
      - userdb

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
